### ISSUE TITLE
Example broken by withr 3.0.0

### ISSUE THREAD

**Issue by MichaelChirico** [arnaudgallou/plume#70]
See https://github.com/r-lib/withr/issues/256. `withr::local_tempfile()` may not have been working as you intended, and definitely no longer works under {withr} 3.0.0 (when executed in certain ways):

https://github.com/arnaudgallou/plume/blob/67d86d5c59dfeb21e731d7d1beb5682ef2c03f8c/man/PlumeQuarto.Rd#L14-L17

I confirmed this by running:

```r
devtools::check_examples(document = FALSE)
```

The linked issue cites a few ways to proceed, you can choose which is most appealing to you.

**Comment by arnaudgallou** [comment]
Thanks for the heads up!
